[Include]
Include=../debian-server

[Content]
Packages=
        gdm3
        task-gnome-desktop
        gnome-terminal
        network-manager
        xserver-xorg
        xinit
#KernelCommandLine=selinux=0 console=ttyS0,115200
PostInstallationScripts=mkosi-postinst-desktop.sh.chroot
#ExtraTrees=mkosi.overlay.d

[Output]
ImageId=debian-desktop

[Runtime]
QemuArgs=-device virtio-gpu-pci -display gtk